# Generated by Django 4.1.5 on 2023-01-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='main_img',
            field=models.ImageField(default='', upload_to='mainImages/', verbose_name='الصورة الرئيسية'),
            preserve_default=False,
        ),
    ]
