# Generated by Django 4.1.5 on 2023-02-11 18:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم النشاط')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'المؤلفون',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان القسم (بالإنجليزية)')),
                ('name', models.CharField(max_length=200, verbose_name='القسم')),
                ('img', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='صورة المصنف')),
                ('background_hex', models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخلفية')),
                ('color_hex', models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخط')),
                ('view_in_home', models.BooleanField(default=False, verbose_name='عرض في الصفحة الرئيسية')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'اﻷقسام',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
            },
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'محقق',
                'verbose_name_plural': 'المحققين',
            },
        ),
        migrations.CreateModel(
            name='CoverArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'فنان غلاف',
                'verbose_name_plural': 'فنانين الأغلفة',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المجال')),
            ],
            options={
                'verbose_name': 'مجال',
                'verbose_name_plural': 'المجالات',
            },
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='اسم الصيغة')),
            ],
            options={
                'verbose_name': 'صيغة مصنف',
                'verbose_name_plural': 'صيغ المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الشكل')),
            ],
            options={
                'verbose_name': 'شكل مصنف',
                'verbose_name_plural': 'أشكال المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اللغة')),
            ],
            options={
                'verbose_name': 'لغة',
                'verbose_name_plural': 'اللغات',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='القياس')),
            ],
            options={
                'verbose_name': 'قياس مصنف',
                'verbose_name_plural': 'قياسات المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Mosannaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المصنف')),
                ('meaning', models.TextField(verbose_name='تفسير اسم المصنف')),
                ('summary', models.TextField(verbose_name='نبذه عن المصنف')),
                ('chain', models.CharField(max_length=200, verbose_name='سلسلة')),
                ('date_published', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('parts_count', models.IntegerField(default=0, verbose_name='الأجزاء')),
                ('pages_count', models.IntegerField(default=0, verbose_name='الصفحات')),
                ('units_count', models.IntegerField(default=0, verbose_name='اﻷبواب')),
                ('chapters_count', models.IntegerField(default=0, verbose_name='الفصول')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموضوع')),
                ('chapter', models.CharField(max_length=200, verbose_name='الفصل')),
                ('field', models.CharField(max_length=200, verbose_name='المجال')),
                ('activity', models.CharField(max_length=200, verbose_name='النشاط')),
                ('image', models.ImageField(upload_to='covers/', verbose_name='صورة المصنف')),
                ('file', models.FileField(upload_to='mosannafat/', verbose_name='ملف المصنف')),
                ('m_size', models.CharField(max_length=200, verbose_name='حجم المصنف')),
                ('print_year', models.CharField(max_length=20, verbose_name='سنة الطباعة')),
                ('print_number', models.CharField(max_length=20, verbose_name='رقم طبعة')),
                ('publish_year', models.CharField(max_length=20, verbose_name='سنة النشر')),
                ('isbn', models.CharField(max_length=50, verbose_name='ردمك')),
                ('issn', models.CharField(max_length=50, verbose_name='ردمد')),
                ('deposit_number', models.CharField(max_length=60, verbose_name='رقم الايداع')),
                ('iso', models.CharField(max_length=200, verbose_name='ايزو')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.author', verbose_name='المؤلف')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.branch', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'مصنف',
                'verbose_name_plural': 'المصنفات',
            },
        ),
        migrations.CreateModel(
            name='MosannafCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='فئة المصنف')),
            ],
            options={
                'verbose_name': 'فئة المصنف',
                'verbose_name_plural': 'فئات المصنفات',
            },
        ),
        migrations.CreateModel(
            name='NearLandMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'أقرب معلم بارز',
                'verbose_name_plural': 'أقرب معلم بارز',
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'معد',
                'verbose_name_plural': 'المعدين',
            },
        ),
        migrations.CreateModel(
            name='PrintingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='دولة')),
                ('territory', models.CharField(max_length=100, verbose_name='إقليم')),
                ('county', models.CharField(max_length=100, verbose_name='مقاطعة')),
                ('region', models.CharField(max_length=100, verbose_name='منطقة')),
                ('city', models.CharField(max_length=100, verbose_name='مدينة')),
                ('governorate', models.CharField(max_length=100, verbose_name='محافظة')),
                ('village', models.CharField(max_length=100, verbose_name='قرية')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='حي')),
                ('building', models.IntegerField(default=0, verbose_name='بناية رقم')),
                ('floor', models.IntegerField(default=0, verbose_name='الدور')),
                ('unit', models.CharField(max_length=20, verbose_name='الوحدة')),
                ('coordinates', models.CharField(max_length=100, verbose_name='إحداثيات')),
                ('landline_number', models.CharField(max_length=20, verbose_name='هاتف رقم')),
                ('phone_number', models.CharField(max_length=20, verbose_name='جوال رقم')),
                ('fax_number', models.CharField(max_length=25, verbose_name='فاكس رقم')),
                ('telex', models.CharField(max_length=50, verbose_name='تلكس')),
                ('pobox', models.CharField(max_length=50, verbose_name='صندوق بريد')),
                ('postal_code', models.CharField(max_length=50, verbose_name='الرمز البريدي')),
                ('email', models.EmailField(max_length=150, verbose_name='البريد الإلكتروني')),
                ('nearest_landmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.nearlandmark', verbose_name='أقرب معلم بارز')),
            ],
            options={
                'verbose_name': 'مطبعة',
                'verbose_name_plural': 'المطابع',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='دولة')),
                ('territory', models.CharField(max_length=100, verbose_name='إقليم')),
                ('county', models.CharField(max_length=100, verbose_name='مقاطعة')),
                ('region', models.CharField(max_length=100, verbose_name='منطقة')),
                ('city', models.CharField(max_length=100, verbose_name='مدينة')),
                ('governorate', models.CharField(max_length=100, verbose_name='محافظة')),
                ('village', models.CharField(max_length=100, verbose_name='قرية')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='حي')),
                ('building', models.IntegerField(default=0, verbose_name='بناية رقم')),
                ('floor', models.IntegerField(default=0, verbose_name='الدور')),
                ('unit_number', models.IntegerField(default=0, verbose_name='رقم الوحدة')),
                ('coordinates', models.CharField(max_length=100, verbose_name='إحداثيات')),
                ('landline_number', models.CharField(max_length=20, verbose_name='هاتف رقم')),
                ('phone_number', models.CharField(max_length=20, verbose_name='جوال رقم')),
                ('fax_number', models.CharField(max_length=25, verbose_name='فاكس رقم')),
                ('telex', models.CharField(max_length=50, verbose_name='تلكس')),
                ('pobox', models.CharField(max_length=50, verbose_name='صندوق بريد')),
                ('postal_code', models.CharField(max_length=50, verbose_name='الرمز البريدي')),
                ('email', models.EmailField(max_length=150, verbose_name='البريد الإلكتروني')),
                ('p_range', models.CharField(max_length=100, verbose_name='النطاق')),
                ('nearest_landmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.nearlandmark', verbose_name='أقرب معلم بارز')),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'الناشرون',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الحجم')),
            ],
            options={
                'verbose_name': 'حجم مصنف',
                'verbose_name_plural': 'أحجام المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='شارع')),
            ],
            options={
                'verbose_name': 'شارع',
                'verbose_name_plural': 'شوارع',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'المواضيع',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نوع المصنف')),
            ],
            options={
                'verbose_name': 'نوع المصنف',
                'verbose_name_plural': 'أنوع المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='باب')),
            ],
            options={
                'verbose_name': 'باب',
                'verbose_name_plural': 'الأبواب',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'نوع وحدة قياس',
                'verbose_name_plural': 'نوع وحدة القياس',
            },
        ),
        migrations.CreateModel(
            name='TranslatedMosannaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_published', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار المترجم')),
                ('translate_publisher', models.CharField(max_length=200, verbose_name='ناشر الترجمة')),
                ('cover', models.ImageField(upload_to='Motargam/Covers', verbose_name='صورة المصنف المترجم')),
                ('tm_form', models.CharField(blank=True, max_length=200, null=True, verbose_name='شكل المصنف')),
                ('tm_size', models.CharField(max_length=100, verbose_name='حجم المصنف المترجم')),
                ('tm_mesaurement', models.CharField(max_length=100, verbose_name='قياس المصنف')),
                ('preparation', models.CharField(max_length=100, verbose_name='اعداد')),
                ('checker', models.CharField(max_length=200, verbose_name='المحقق')),
                ('print_year', models.CharField(max_length=20, verbose_name='سنة الطباعة')),
                ('print_number', models.CharField(max_length=20, verbose_name='رقم الطباعة')),
                ('publish_year', models.CharField(max_length=20, verbose_name='سنة النشر')),
                ('translation_isbn', models.CharField(max_length=50, verbose_name='ردمك الترجمة')),
                ('issn', models.CharField(max_length=50, verbose_name='ردمد')),
                ('deposit_number', models.CharField(max_length=60, verbose_name='رقم الايداع')),
                ('iso', models.CharField(max_length=200)),
                ('cover_artist', models.CharField(max_length=200, verbose_name='فنان الغلاف')),
                ('chain', models.CharField(max_length=100, verbose_name='السلسلة')),
                ('branch', models.CharField(max_length=100, verbose_name='القسم')),
                ('fields', models.ManyToManyField(to='mosannaf.field', verbose_name='المجالات')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.lang', verbose_name='اللغة')),
                ('mosannaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosannaf.mosannaf', verbose_name='المصنف')),
                ('printing_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.printinghouse', verbose_name='المطبعة')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.publisher', verbose_name='الناشر')),
                ('tm_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.formats', verbose_name='صيغة المترجم')),
            ],
            options={
                'verbose_name': 'مصنف مترجم',
                'verbose_name_plural': 'مصنف مترجم',
            },
        ),
        migrations.CreateModel(
            name='SubBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='القسم الفرعي')),
                ('img', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='صورة المصنف')),
                ('background_hex', models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخلفية')),
                ('color_hex', models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخط')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='الاسم الظاهر في الرابط')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosannaf.branch', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'قسم فرعي للمكتبة',
                'verbose_name_plural': 'اﻷقسام الفرعية للمكتبة',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250, verbose_name='التقييم')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='عدد النجوم')),
                ('mosannaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosannaf_rate', to='mosannaf.mosannaf', verbose_name='المصنف')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.street', verbose_name='شارع'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.unittype', verbose_name='نوع الوحدة'),
        ),
        migrations.AddField(
            model_name='printinghouse',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.street', verbose_name='شارع'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.mosannafcategory', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.checker', verbose_name='المحقق'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosannaf_competitor', to='mosannaf.mosannaf', verbose_name='منافس'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='contrary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosannaf_contrary', to='mosannaf.mosannaf', verbose_name='منافي'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='cover_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.coverartists', verbose_name='فنان الغلاف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='fields',
            field=models.ManyToManyField(to='mosannaf.field', verbose_name='المجالات'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='m_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.forms', verbose_name='شكل المصنف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='m_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.formats', verbose_name='صيغة المصنف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='m_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.type', verbose_name='نوع المصنف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.measurement', verbose_name='قياس المصنف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='original_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.lang', verbose_name='أصل لغة المصنف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.preparation', verbose_name='إعداد'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='printing_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.printinghouse', verbose_name='المطبعة'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.publisher', verbose_name='ناشر'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosannaf_related_to', to='mosannaf.mosannaf', verbose_name='ذو علاقة'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.specialization', verbose_name='التخصصص'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='sub_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.subbranch', verbose_name='القسم الفرعي'),
        ),
    ]
