# Generated by Django 4.1.3 on 2022-12-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subbranch",
            options={
                "verbose_name": "قسم فرعي للمكتبة",
                "verbose_name_plural": "اﻷقسام الفرعية للمكتبة",
            },
        ),
        migrations.AlterModelOptions(
            name="translatedmosannaf",
            options={"verbose_name": "مصنف مترجم", "verbose_name_plural": "مصنف مترجم"},
        ),
        migrations.AlterModelOptions(
            name="unittype",
            options={
                "verbose_name": "نوع وحدة قياس",
                "verbose_name_plural": "نوع وحدة القياس",
            },
        ),
    ]
