# Generated by Django 4.1.5 on 2023-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0002_alter_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosannaf',
            name='image',
            field=models.ImageField(upload_to='covers/', verbose_name='صورة المصنف'),
        ),
    ]
