# Generated by Django 4.1.3 on 2022-12-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0002_alter_subbranch_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mosannaf",
            name="sub_brnach",
        ),
        migrations.RemoveField(
            model_name="mosannaf",
            name="unit",
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="chain",
            field=models.CharField(default="", max_length=200, verbose_name="سلسلة"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="sub_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.subbranch",
                verbose_name="القسم الفرعي",
            ),
        ),
    ]
