# Generated by Django 4.1.5 on 2023-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0003_alter_mosannaf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosannaf',
            name='file',
            field=models.FileField(upload_to='mosannafat/', verbose_name='ملف المصنف'),
        ),
    ]
