# Generated by Django 4.1.5 on 2023-02-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0003_alter_rate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosannaf',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='الاسم الظاهر في الرابط'),
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم المصنف'),
        ),
    ]
