# Generated by Django 4.1.3 on 2022-12-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0003_remove_mosannaf_sub_brnach_remove_mosannaf_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatedmosannaf",
            name="fields",
            field=models.ManyToManyField(blank=True, null=True, to="mosannaf.field"),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(max_length=150, verbose_name="اسم المجال"),
        ),
    ]
