# Generated by Django 4.1.3 on 2022-12-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0003_remove_mosannaf_sub_brnach_remove_mosannaf_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosannaf",
            name="branch",
            field=models.CharField(default="", max_length=200, verbose_name="القسم"),
            preserve_default=False,
        ),
    ]
