# Generated by Django 4.1.3 on 2022-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0004_translatedmosannaf_fields_alter_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatedmosannaf",
            name="fields",
            field=models.ManyToManyField(
                blank=True, null=True, to="mosannaf.field", verbose_name="المجالات"
            ),
        ),
    ]
