# Generated by Django 4.1.5 on 2023-02-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0004_mosannaf_slug_alter_mosannaf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='nearest_landmark',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='street',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='unit_type',
        ),
        migrations.AlterModelOptions(
            name='translatedmosannaf',
            options={'verbose_name': 'ناشر', 'verbose_name_plural': 'الناشرون'},
        ),
        migrations.AddField(
            model_name='translatedmosannaf',
            name='p_range',
            field=models.CharField(default='', max_length=100, verbose_name='النطاق'),
            preserve_default=False,
        ),
    ]
