# Generated by Django 4.1.5 on 2023-02-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0005_remove_publisher_nearest_landmark_and_more'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosannaf',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.publisher', verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='translatedmosannaf',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.publisher', verbose_name='الناشر'),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
