# Generated by Django 4.1.5 on 2023-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0005_alter_rate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='عنوان القسم (بالإنجليزية)'),
            preserve_default=False,
        ),
    ]
