# Generated by Django 4.1.3 on 2022-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0005_alter_translatedmosannaf_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosannaf",
            name="print_number",
            field=models.CharField(max_length=20, verbose_name="رقم طبعة"),
        ),
    ]
