# Generated by Django 4.1.3 on 2022-12-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0006_alter_mosannaf_print_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translatedmosannaf",
            name="fields",
        ),
    ]
