# Generated by Django 4.1.5 on 2023-02-02 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0006_branch_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='stars',
        ),
        migrations.AddField(
            model_name='rate',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='عدد النجوم'),
        ),
    ]
