# Generated by Django 4.1.3 on 2022-12-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0007_remove_translatedmosannaf_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printingbranch",
            options={
                "verbose_name": "قسم مطبعة",
                "verbose_name_plural": "أقسام المطبعة",
            },
        ),
    ]
