# Generated by Django 4.1.5 on 2023-02-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0007_remove_rate_stars_rate_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='MosannafCategory',
        ),
    ]
