# Generated by Django 4.1.3 on 2022-12-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0008_alter_printingbranch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosannaf",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.branch",
                verbose_name="القسم",
            ),
        ),
    ]
