# Generated by Django 4.1.5 on 2023-02-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0009_branch_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='background_hex',
            field=models.CharField(default='#212121', max_length=20, verbose_name='كود Hex لون الخلفية'),
            preserve_default=False,
        ),
    ]
