# Generated by Django 4.1.3 on 2022-12-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0009_alter_mosannaf_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printinghouse",
            name="branch",
        ),
        migrations.DeleteModel(
            name="PrintingBranch",
        ),
    ]
