# Generated by Django 4.1.5 on 2023-02-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0010_branch_background_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='color_hex',
            field=models.CharField(default='#f9f9f9', max_length=20, verbose_name='كود Hex لون الخط'),
            preserve_default=False,
        ),
    ]
