# Generated by Django 4.1.3 on 2022-12-31 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0011_coverartists_alter_mosannaf_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosannaf",
            name="related_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.mosannaf",
                verbose_name="ذو علاقة",
            ),
        ),
    ]
