# Generated by Django 4.1.5 on 2023-02-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0011_branch_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='background_hex',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخلفية'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='color_hex',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخط'),
        ),
    ]
