# Generated by Django 4.1.5 on 2023-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0012_alter_branch_background_hex_alter_branch_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbranch',
            name='background_hex',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخلفية'),
        ),
        migrations.AddField(
            model_name='subbranch',
            name='color_hex',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='كود Hex لون الخط'),
        ),
        migrations.AddField(
            model_name='subbranch',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='صورة المصنف'),
        ),
    ]
