# Generated by Django 4.1.3 on 2022-12-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0013_specialization_alter_mosannaf_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosannaf",
            name="competitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mosannaf_competitor",
                to="mosannaf.mosannaf",
                verbose_name="منافس",
            ),
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="contrary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mosannaf_contrary",
                to="mosannaf.mosannaf",
                verbose_name="منافي",
            ),
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.specialization",
                verbose_name="الفئة",
            ),
        ),
        migrations.AlterField(
            model_name="mosannaf",
            name="related_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mosannaf_related_to",
                to="mosannaf.mosannaf",
                verbose_name="ذو علاقة",
            ),
        ),
    ]
