# Generated by Django 4.1.3 on 2022-12-31 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0014_mosannaf_competitor_mosannaf_contrary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosannaf",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.specialization",
                verbose_name="التخصصص",
            ),
        ),
    ]
