# Generated by Django 4.1.3 on 2023-01-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0015_alter_mosannaf_specialization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="شارع")),
            ],
            options={
                "verbose_name": "شارع",
                "verbose_name_plural": "شوارع",
            },
        ),
        migrations.AlterField(
            model_name="printinghouse",
            name="street",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.street",
                verbose_name="شارع",
            ),
        ),
    ]
