# Generated by Django 4.1.3 on 2023-01-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0016_street_alter_printinghouse_street"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearLandMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم")),
            ],
            options={
                "verbose_name": "أقرب معلم بارز",
                "verbose_name_plural": "أقرب معلم بارز",
            },
        ),
    ]
