# Generated by Django 4.1.3 on 2023-01-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0017_nearlandmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printinghouse",
            name="nearest_landmark",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.nearlandmark",
                verbose_name="أقرب معلم بارز",
            ),
        ),
    ]
