# Generated by Django 4.1.3 on 2023-01-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0018_alter_printinghouse_nearest_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="nearest_landmark",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.nearlandmark",
                verbose_name="أقرب معلم بارز",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="street",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.street",
                verbose_name="شارع",
            ),
        ),
    ]
