# Generated by Django 4.1.3 on 2023-01-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0019_alter_publisher_nearest_landmark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosannaf",
            name="fields",
            field=models.ManyToManyField(to="mosannaf.field", verbose_name="المجالات"),
        ),
    ]
