# Generated by Django 4.1.3 on 2023-01-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0020_mosannaf_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatedmosannaf",
            name="fields",
            field=models.ManyToManyField(to="mosannaf.field", verbose_name="المجالات"),
        ),
    ]
