# Generated by Django 4.1.3 on 2023-01-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0021_translatedmosannaf_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialization",
            options={"verbose_name": "تخصص", "verbose_name_plural": "التخصصات"},
        ),
    ]
